language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer install
  - cd vendor/simettric/serenity-bundle/Simettric/SerenityBundle
  - composer update
  - cd ../../../../../


script: phpunit -c app
